config/routes.rb
Rails.application.routes.draw do
  get '/' => 'main#index'
  get '/new' => 'main#new'
  post '/create' => 'main#create'
  delete '/destroy' => 'main#destroy'
  get 'signup'  => 'users#new'
  resources :users
  get 'login' => 'sessions#new'
  resources :sessions
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :main, only: [:index, :new, :create, :destroy]
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attached_file.rb
class AttachedFile < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def set_user
    if !current_user
      redirect_to '/login'
      return
    end
    @user = current_user
  end

  def new
    @attached_file = AttachedFile.new
  end

  def index
    set_user
    @attached_files = AttachedFile.all
  end

  def create
    @attached_file = AttachedFile.new(file_params)
    if @attached_file.save
      redirect_to '/', notice: "The file #{@attached_file.name} has been uploaded."
    else
      render :new
    end
  end

  def destroy
    @attached_file = AttachedFile.find(params[:id])
    @attached_file.destroy
    redirect_to '/', notice:  "The file #{@attached_file.name} has been deleted."
  end

  private
  def file_params
    params.require(:attached_file).permit(:name, :attachment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash.now[:error] = "Invalid email or password"
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.find_by_email(@user.email)
      flash.now[:error] = "Such user already exists"
      render :new
    elsif user_params['password'] != user_params['password_confirmation']
      flash.now[:error] = "Passwords do not match"
      render :new
    else
      if @user.save
        session[:user_id] = @user.id
        redirect_to '/'
      else
        redirect_to '/signup'
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attached_files_helper.rb
module AttachedFilesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/create.html.erb
<h1>AttachedFiles#create</h1>
<p>Find me in app/views/attached_files/create.html.erb</p>

app/views/main/destroy.html.erb
<h1>AttachedFiles#destroy</h1>
<p>Find me in app/views/attached_files/destroy.html.erb</p>

app/views/main/index.html.erb
<div>
  <nav class="navbar navbar-dark bg-faded justify-content-between">
    <a class="navbar-brand">PDF Loader</a>
    <form class="form-inline">
      <%= link_to "New File", "/new", class: "btn btn-outline-success" %>
      <div class="dropdown">
        <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
          <%= @user.first_name %> <%= @user.last_name %>
        </button>
        <ul class="dropdown-menu">
          <li><a href="/logout">Logout</a></li>
        </ul>
      </div>
    </form>
  </nav>
  <div>
    <% if !flash[:notice].blank? %>
      <div class = "alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <br />
    <table class = "table table-bordered table-striped">
      <thead>.
      <tr>
        <th>Name</th>
        <th>Download Link</th>
        <th> </th>
      </tr>
      </thead>

      <tbody>
      <% @attached_files.each do |attached_file| %>

        <tr>
          <td><%= attached_file.name %></td>
          <td><%= link_to "Download File", attached_file.attachment_url %></td>
          <td><%= button_to "Delete", main_path(attached_file), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{attached_file.name}?" %></td>
        </tr>

      <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/main/new.html.erb
<% if !@attached_file.errors.empty? %>
  <div class = "alert alert-error">

    <ul>
      <% @attached_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<div class="well">
  <%= form_for @attached_file, :url => '/create', html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="content" id="signup">
  <div class="form-group">
        <h1>Sign up</h1>
        <%= form_for(@user) do |f| %>
          <% if flash[:error] -%>
            <div class="alert alert-danger" role="alert">
              <p class="error"><%= flash[:error] %></p>
            </div>
          <% end -%>
          <%= f.text_field :first_name, :placeholder => "First name", class: 'form-control'%>
          <%= f.text_field :last_name, :placeholder => "Last name", class: 'form-control' %>
          <%= f.email_field :email, :placeholder => "Email", class: 'form-control'%>
          <%= f.password_field :password, :placeholder => "Password", class: 'form-control'%>
          <%= f.password_field :password_confirmation, :placeholder => "Confirm password", class: 'form-control'%>
          <div class="buttons">
            <%= f.submit "Create an account", class: "btn btn-primary" %>
            <a href="/login">Login</a>
          </div>
        <% end %>
  </div>
</div>